config/routes.rb
module RouteScope
  def self.root
    Rails.application.config.root_directory
  rescue NameError
    '/'
  end
end

Rails.application.routes.draw do
  scope RouteScope.root do

    root :to => proc { [404, {}, ['Not found.']] }

    resources :messages, :only => [:new, :create] do
      collection do
        get :success
      end
    end

    resources :projects, :only => [:index] do
      member do
        get :disabled
      end
    end

    resources :preorders, :only => [:new, :create] do
      collection do
        get :success
        get :confirm
      end
    end

    resources :testfdc_results, :only => [:index, :new, :create] do
      collection do
        get :success
      end
    end

    namespace :api, :constraints => { :format => 'json' } do
      resources :testfdc_notes, :only => [:index, :show, :create]

      resources :testfdc_results, :only => [:index, :destroy, :create, :show, :update] do
        collection do
          get :unapproved
        end

        member do
          patch :approve
        end
      end

    end
  end
end

app/models/testfdc_result.rb
class TestfdcResult < ApplicationRecord
  belongs_to :note, :class_name => 'TestfdcNote'

  validate :at_least_one_field_populated

  RESULT_OPTIONS = [['Pass', 1], ['Fail', 0], ['Not Tested', '']]
  NOT_TESTED = ''

  delegate :test_result, :to => :class

  def approve!
    self.update!(:approved => true)
  end

  def result_string=(results)
    self.fm_250 = process_result_string_character(results[0])
    self.mfm_250 = process_result_string_character(results[1])
    self.mfm_250_128 = process_result_string_character(results[2])

    self.fm_300 = process_result_string_character(results[4])
    self.mfm_300 = process_result_string_character(results[5])
    self.mfm_300_128 = process_result_string_character(results[6])

    self.fm_500 = process_result_string_character(results[8])
    self.mfm_500 = process_result_string_character(results[9])
    self.mfm_500_128 = process_result_string_character(results[10])
  end

  def result_string
    return_string = "#{test_result(fm_250)}#{test_result(mfm_250)}#{test_result(mfm_250_128)} "
    return_string += "#{test_result(fm_300)}#{test_result(mfm_300)}#{test_result(mfm_300_128)} "
    return_string += "#{test_result(fm_500)}#{test_result(mfm_500)}#{test_result(mfm_500_128)}"
    return_string
  end

  def to_report_s
    "#{padded_manufacturer} #{padded_model} #{padded_fdc_chip} #{padded_class} #{result_string} #{note_number_or_blank}"
  end

  # BEGIN Class Methods

  def self.test_result(input)
    return 'N' if input.nil?
    input ? 'P' : 'F'
  end

  # END Class Methods

  private

  def at_least_one_field_populated
    unless manufacturer.present? || model.present? || fdc_chip.present?
      errors.add :base, 'You submitted a blank report; you must fill in something!'
    end
  end

  def fixed_length(input, length)
    (input || '').slice(0...length).ljust(length)
  end

  def note_number_or_blank
    note.number if note.present?
  end

  def padded_manufacturer
    fixed_length(manufacturer, 15)
  end

  def padded_model
    fixed_length(model, 23)
  end

  def padded_fdc_chip
    fixed_length(fdc_chip, 15)
  end

  def padded_class
    fixed_length(hardware_class, 7)
  end

  def process_result_string_character(result_char)
    return true if result_char == 'P'
    return false if result_char == 'F'
    nil
  end
end

app/controllers/api/testfdc_results_controller.rb
class Api::TestfdcResultsController < Api::ApiController

  before_action :load_testfdc_result, :only => [:show, :update, :destroy, :approve]

  def index
    render :json => TestfdcResult.order(:manufacturer).to_a
  end

  def show
    render :json => @testfdc_result
  end

  def create
    result = TestfdcResult.new(testfdc_result_parameters)

    if result.valid?
      result.save!
      head 201
    else
      render :json => result.errors, :status => 422
    end
  end

  def update
    @testfdc_result.update(testfdc_result_parameters)

    if @testfdc_result.valid?
      @testfdc_result.save!
      head 204
    else
      render :json => @testfdc_result.errors, :status => 422
    end
  end

  def destroy
    @testfdc_result.destroy!
    head 204
  end

  def unapproved
    render :json => TestfdcResult.where(:approved => nil).to_a
  end

  def approve
    @testfdc_result.approve!
    head 204
  end

  private

  def load_testfdc_result
    @testfdc_result = TestfdcResult.find(params[:id])
  end

  def testfdc_result_parameters
    params.require(:testfdc_result).permit(
      :manufacturer,
      :model,
      :fdc_chip,
      :hardware_class,
      :fm_250,
      :fm_300,
      :fm_500,
      :mfm_250,
      :mfm_300,
      :mfm_500,
      :mfm_250_128,
      :mfm_300_128,
      :mfm_500_128,
      :approved,
      :note_id
    )
  end
end

app/controllers/testfdc_results_controller.rb
class TestfdcResultsController < ApplicationController

  def index
    @testfdc_results = TestfdcResult.where(:approved => true).order(:manufacturer).to_a
    @notes = TestfdcNote.order(:number).to_a
    @latest_entry = TestfdcResult.where(:approved => true).order(:updated_at => :desc).first.updated_at if @testfdc_results.any?
  end

  def new
    @testfdc_result = TestfdcResult.new
  end

  def create
    @testfdc_result = TestfdcResult.new(testfdc_result_parameters)

    if @testfdc_result.valid? && @testfdc_result.save!
      redirect_to success_testfdc_results_path
    else
      render :new
    end
  end

  private

  def testfdc_result_parameters
    params.require(:testfdc_result).permit(
      :manufacturer,
      :model,
      :fdc_chip,
      :hardware_class,
      :fm_250,
      :fm_300,
      :fm_500,
      :mfm_250,
      :mfm_300,
      :mfm_500,
      :mfm_250_128,
      :mfm_300_128,
      :mfm_500_128,
      :initial_report_notes
    )
  end
end

app/views/testfdc_results/index.html.erb
<% @page_title = "TestFDC Results Registry" %>

<p>This page is also available in <%= link_to 'plaintex format', testfdc_results_path(:format => 'text') %></p>

<p>Updated <%= @latest_entry %></p>

<p>This page contains a listing of motherboards and/or floppy controllers that have been tested with Dave Dunfield's <%= link_to 'TESTFDC program', 'http://dunfield.classiccmp.org/img/index.htm' %> His registry seems to be in an unmaintaned state, so we've put this one together to try and keep the registry updated. As with Dave's original registry, there is no guarantee that this information is correct.</p>

<p>You may submit your results using the <%= link_to 'TestFDC results submission form', new_testfdc_result_path %>. You may also submit results using our general-purpose <%= link_to 'contact form', new_message_path %>.</p>

<h2>Useful Information</h2>

<p>All mainboards should pass the 'D' tests - these are required for standard PC formats.</p>

<p>A mainboard that fails all 'S' tests will not be able to read or recreate single-density disks, which account for a significant portion of older non-
PC formats.</p>

<p>A mainboard that passes the 250 and 500kpbs 'S' tests, but fails the 300kbps 'S' test will not be able to handle single-density with a 1.2M 5.25" HD drive (the most common 5.25" drive types in AT and later machines), however it will be able to do it if you install a DD drive. (Use of a DD drive is recommended for SD/DD formats anyway, even if the HD setup supports it).</p>

<p>The 'X' test (Double-Density with 128 bytes sectors) checks a capability that is used by very few disk formats, and for most people, not having it will not be a significant drawback. (Which is good, because the original NEC-765 PC controller, and most later chips based on this design don't support it).</p>

<h2>Interpreting The Results Registry Table</h2>

<pre>
S = Single Density                              P = Passed
D = Double Density                              F = Failed
X = Double Density / 128 Byte Sectors           N = Not tested

? or blank = information not submitted

Entries with no model were provided for the FDC chip only
</pre>

<br />
<table class='centered-wide'>
  <thead>
    <tr>
      <td colspan='4'></td>
      <th colspan='9'>Data Rate</th>
    </tr>
    <tr>
      <td colspan='4'></td>
      <th colspan='3'>250</th>
      <th colspan='3'>300</th>
      <th colspan='3'>500</th>
    </tr>
    <tr>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>FDC Chip</th>
      <th>Class</th>
      <th>S</th>
      <th>D</th>
      <th>X</th>
      <th>S</th>
      <th>D</th>
      <th>X</th>
      <th>S</th>
      <th>D</th>
      <th>X</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <% @testfdc_results.each do |result| %>
      <tr class='hilight-row'>
        <td><%= result.manufacturer %></td>
        <td><%= result.model %></td>
        <td><%= result.fdc_chip %></td>
        <td><%= result.hardware_class %></td>
        <td class='center'><%= test_result(result.fm_250) %></td>
        <td class='center'><%= test_result(result.mfm_250) %></td>
        <td class='center'><%= test_result(result.mfm_250_128) %></td>
        <td class='center'><%= test_result(result.fm_300) %></td>
        <td class='center'><%= test_result(result.mfm_300) %></td>
        <td class='center'><%= test_result(result.mfm_300_128) %></td>
        <td class='center'><%= test_result(result.fm_500) %></td>
        <td class='center'><%= test_result(result.mfm_500) %></td>
        <td class='center'><%= test_result(result.mfm_500_128) %></td>
        <td class='center'><%= result.note.number if result.note.present? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Notes</h2>

<ol>
  <% @notes.each do |note| %>
    <li><%= note.description %></li>
  <% end %>
</ol>

app/views/testfdc_results/index.text.erb
Updated <%= @latest_entry %>

This document contains a listing of mainboards and floppy controllers that
have been tested with Dave Dunfield's TESTFDC program. His registry seems to 
be in an unmaintaned state, so we've put this one together to try and keep the
registry updated. As with Dave's original registry, there is no guarantee that
this information is correct.

You may submit your results using the TestFDC results submission form:

<%= url_for new_testfdc_result_url %> 

You may also submit results using our general-purpose contact form:

<%= url_for new_message_url %>

----------------------------- Useful  Information ----------------------------

All mainboards should pass the 'D' tests - these are required for standard PC
formats.

A mainboard that fails all 'S' tests will not be able to read or recreate
single-density disks, which account for a significant portion of older non-
PC formats.

A mainboard that passes the 250 and 500kpbs 'S' tests, but fails the 300kbps
'S' test will not be able to handle single-density with a 1.2M 5.25" HD drive
(the most common 5.25" drive types in AT and later machines), however it will
be able to do it if you install a DD drive. (Use of a DD drive is recommended
for SD/DD formats anyway, even if the HD setup supports it).

The 'X' test (Double-Density with 128 bytes sectors) checks a capability that
is used by very few disk formats, and for most people, not having it will not
be a significant drawback. (Which is good, because the original NEC-765 PC
controller, and most later chips based on this design don't support it).

---------------------- Mainboard / Controller  Listings ----------------------

S = Single Density                              P = Passed
D = Double Density                              F = Failed
X = Double Density / 128 byte sectors           N = Not tested

Entries with no model were provided for the FDC chip only.

                                                                 Data rate
                                                                250 300 500
Manufacturer    Model                   FDC chip        Class   SDX SDX SDX
------------------------------------------------------------------------------
<% @testfdc_results.each do |testfdc_result| %>
<%= testfdc_result.to_report_s %>
<% end %>


Notes:
<% @notes.each do |note| %>
<%= note.to_report_s %>
<% end %>

app/views/testfdc_results/new.html.erb
<% @page_title = 'Add Your TestFDC Results' %>

<%= base_error_explanation @testfdc_result %>

<p>Please fill out as much information as you have from your TestFDC run. Leave untested modes blank. Add any relevant notes in the space provided</p>

<p>Submissions are hand-approved and will not appear in the registry immediately.</p>

<%= simple_form_for @testfdc_result do |f| %>  
  <h2>General Information</h2>

  <%= f.input :manufacturer, :label => 'Hardware manufacturer' %><br />
  <%= f.input :model, :label => 'Hardware model' %><br />
  <%= f.input :fdc_chip, :label => 'FDC controller chip' %><br />
  <%= f.input :hardware_class, :label => 'Hardware class (AT, ATX, ISA card, etc.)' %><br />

  <h2>250 kbps Data Rate</h2>

  <table class='noborder'>
    <tr>
      <td>Single Density (FM):</td>
      <td><%= f.input :fm_250, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
    <tr>
      <td>Double Density (MFM):</td>
      <td><%= f.input :mfm_250, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
    <tr>
      <td>Double Density (MFM) with 128 Byte Sectors:</td>
      <td><%= f.input :mfm_250_128, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
  </table>

  <h2>300 kbps Data Rate</h2>

  <table class='noborder'>
    <tr>
      <td>Single Density (FM):</td>
      <td><%= f.input :fm_300, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
    <tr>
      <td>Double Density (MFM):</td>
      <td><%= f.input :mfm_300, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
    <tr>
      <td>Double Density (MFM) with 128 Byte Sectors:</td>
      <td><%= f.input :mfm_300_128, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
  </table>

  <h2>500 kbps Data Rate</h2>

  <table class='noborder'>
    <tr>
      <td>Single Density (FM):</td>
      <td><%= f.input :fm_500, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
    <tr>
      <td>Double Density (MFM):</td>
      <td><%= f.input :mfm_500, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
    <tr>
      <td>Double Density (MFM) with 128 Byte Sectors:</td>
      <td><%= f.input :mfm_500_128, :label => false, :as => :radio_buttons, :collection => TestfdcResult::RESULT_OPTIONS, :checked => TestfdcResult::NOT_TESTED%></td>
    </tr>
  </table>

  <h2>Additional Notes</h2>

  <p>Notes provided here will be distilled down and turned into footnote-style notes, as seen in the main registry table.</p>

  <%= f.input :initial_report_notes, :label => false, :input_html => { :class => 'full-width', :rows => 20 } %>

  <br />

  <%= f.button :submit, 'Submit Your TestFDC Results' %>
<% end %>

app/views/testfdc_results/success.html.erb
<% @page_title = 'TestFDC Result Submitted' %>

Thanks for your TestFDC results submission! It will be reviewed shortly.

<%= link_to 'Return to the TestFDC Registry', testfdc_results_path %>