config/routes.rb
module RouteScope
  def self.root
    Rails.application.config.root_directory
  rescue NameError
    '/'
  end
end

Rails.application.routes.draw do
  scope RouteScope.root do

    root :to => proc { [404, {}, ['Not found.']] }

    resources :messages, :only => [:new, :create] do
      collection do
        get :success
      end
    end

    resources :projects, :only => [:index] do
      member do
        get :disabled
      end
    end

    resources :preorders, :only => [:new, :create] do
      collection do
        get :success
        get :confirm
      end
    end

    resources :testfdc_results, :only => [:index, :new, :create] do
      collection do
        get :success
      end
    end

    namespace :api, :constraints => { :format => 'json' } do
      resources :testfdc_notes, :only => [:index, :show, :create]

      resources :testfdc_results, :only => [:index, :destroy, :create, :show, :update] do
        collection do
          get :unapproved
        end

        member do
          patch :approve
        end
      end

    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :preorders

  validates :name, :presence => true, :uniqueness => { :case_sensitive => true }
  validates :printable_name, :presence => true

  def confirmed_preorders
  	preorders.confirmed
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_project, :only => :disabled

  def disabled
  end

  def index
    @projects = Project.where(:enabled => true).order(:printable_name)
  end

  private

  def load_project
    @project = Project.find_by!(:name => params[:id])
  end
end

app/views/projects/disabled.html.erb
<% @page_title = "#{@project.printable_name} Project is Disabled" %>

The project you requested is currently disabled. No preorders can be submitted at this time.

app/views/projects/index.html.erb
<% @page_title = "All Active Projects" %>

<p>This is a list of all active projects, their creation dates, and the number of confirmed preorders associated with them. Click the Sign Up for Preorder link to add your information to the preorder for that specific project.</p>

<p>When enough confirmed preorders exist to meet the price target for a project, the preorder will be closed and you will receive an email at the address you used to confirm your preorder with further instructions. There is no financial obligation until the preorder closes and you agree to the price and terms specified in the email. If you have any questions please <%= link_to 'contact us', new_message_path %>.</p>

<br />
<table class='centered-wide'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Created</th>
      <th>Confirmed Preorders</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr class='hilight-row'>
        <td><%= project.printable_name %></td>
        <td align='right'><%= project.created_at.to_date %></td>
        <td align='right'><%= project.confirmed_preorders.size %></td>
        <td><%= link_to 'Sign Up for Preorder', new_preorder_path(:project => project.name) %></td>
      </tr>
    <% end %>
  </tbody>
</table>